import 'package:giovani_debiagi_webpage/features/flutter_projects/presentation/blocs/flutter_projects_events/i_get_flutter_projects_event.dart';

class GetFlutterProjectsEvent implements IGetFlutterProjectsEvent {}
