// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxkC-F0vQt3QIhL2Mh5DH9sV4m25nEp7c',
    appId: '1:109687985072:web:ef794ee8631382ba247c75',
    messagingSenderId: '109687985072',
    projectId: 'giovani-debiagi-website',
    authDomain: 'giovani-debiagi-website.firebaseapp.com',
    storageBucket: 'giovani-debiagi-website.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lx3UKWPLQDBXEpTcH5VBnWCoBgccFq4',
    appId: '1:109687985072:android:41413657499a48b6247c75',
    messagingSenderId: '109687985072',
    projectId: 'giovani-debiagi-website',
    storageBucket: 'giovani-debiagi-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKCNteyM9zr6UEqzvVO7Lcx8tmJItJiNY',
    appId: '1:109687985072:ios:58f894847ee59c9c247c75',
    messagingSenderId: '109687985072',
    projectId: 'giovani-debiagi-website',
    storageBucket: 'giovani-debiagi-website.appspot.com',
    iosClientId: '109687985072-8jro7r22nvv44ncnm6nk2567srq4u21e.apps.googleusercontent.com',
    iosBundleId: 'com.example.giovaniDebiagiWebpage',
  );
}
